config/routes.rb
Rails.application.routes.draw do
  resources :users
  root "events#index"
  
  resources :events do
    resources :registrations
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord

  has_many :registrations, dependent: :destroy

  validates :name, :location, presence: true

  validates :description, length: { minimum: 25 }

  validates :price, numericality: { greater_than_or_equal_to: 0 }

  validates :capacity, numericality: { only_integer: true, greater_than: 0 }

  validates :image_file_name, format: { with: /\w+\.(jpg|png)\z/i, message: "must be a JPG or PNG image"}

  def self.upcoming
    where("starts_at > ?", Time.now).order("starts_at")
  end

  def free?
    price.blank? || price.zero?
  end

  def sold_out?
    (capacity - registrations.size).zero?
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :event

  validates :name, presence: true

  validates :email, format: { with: /\S+@\S+/ }

  HOW_HEARD_OPTIONS = [
    'Newsletter',
    'Blog Post',
    'Twitter',
    'Web Search',
    'Friend/Coworker',
    'Other'
  ]

  validates :how_heard, inclusion: { in: HOW_HEARD_OPTIONS }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  
  validates :email, format: { with: /\S+@\S+/ }, uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def index
    @events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Event successfully updated!"
    else
      render :edit 
    end
  end
  
  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event, notice: "Event successfully created!"
    else
      render :new
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

private
  def event_params
    params.require(:event).
      permit(:name, :description, :location, :price, :starts_at, :capacity, :image_file_name)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  before_action :set_event

  def index
    @registrations = @event.registrations
  end
  
  def new
    @registration = @event.registrations.new
  end

  def create
    @registration = @event.registrations.new(registration_params)

    if @registration.save
      redirect_to event_registrations_url(@event), notice: "Thanks for registering"
    else
      render :new
    end
  end

private

  def registration_params
    params.require(:registration).permit(:name, :email, :how_heard)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
  
  def price(event)
    if event.free?
      "Free"
    else
      number_to_currency(event.price, precision: 0)
    end
  end

  def day_and_time(event)
    event.starts_at.strftime("%B %d at %I:%M %P")
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
  def register_or_sold_out(event)
    if event.sold_out?
      content_tag(:span, "Sold Out!", class: "sold-out")
    else
      link_to "Register!", new_event_registration_path(event), class: "register"
    end
  end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |f| %>
  
  <%= render "shared/errors", object: event %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :description %>
  <%= f.text_area :description, rows: 5 %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :starts_at %>
  <%= f.datetime_select :starts_at, {ampm: true}, {class: "datetime"} %>

  <%= f.label :capacity %>
  <%= f.number_field :capacity %>

  <%= f.label :image_file_name %>
  <%= f.text_field :image_file_name %>

  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing <%= @event.name %></h1>

<%= render "form", event: @event %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <section class="event">
  <div class="image">
    <%= image_tag event.image_file_name %>
  </div>
    <div class="summary">
      <h2><%= link_to event.name, event_path(event) %></h2>
      <h3><%= day_and_time(event) %> in <%= event.location %></h3>
      <span class="price">
        <%= price(event) %>
      </span>
      <p>
        <%= truncate(event.description, length: 35, separator: ' ') %>
      </p>
    </div>
  </section>   
<% end %>

<section class="admin">
  <%= link_to "Add New Event", new_event_path, class: "button" %>
</section>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= render "form", event: @event %>

app/views/events/show.html.erb
<section class="event-details">
  <div class="image">
    <%= image_tag @event.image_file_name %>
  </div>
  <div class="details">
    <h1><%= @event.name %></h1>
    <h2><%= pluralize(@event.capacity, "spot") %> &bull; <%= price(@event) %></h2>
    <h3><%= day_and_time(@event) %> in <%= @event.location %></h3>
    <p><%= @event.description %></p>
    
    <div class="register">
      <%= register_or_sold_out(@event) %>
      <p>
        <%= link_to "Who's registered?", event_registrations_path(@event) %>
      </p>
    </div>
  </div>
</section>


<section class="admin">
  <%= link_to "Edit", edit_event_path(@event), class: "button" %>
  <%= link_to "Delete", @event, class: "button", method: :delete, data: { confirm: "Really?!" } %>
</section>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash notice">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert] %>
  <div class="flash alert">
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p>
    Made by <a href="http://jasonwai.com">Jason Wai</a>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to image_tag("logo"), root_path %>
    <ul class="left">
      <li>
        <%= link_to "All Events", events_path %>
      </li>
      <li></li>
      <li></li>
    </ul>
    <ul class="right">
      <li>
        <%= link_to "Sign Up", new_user_path, class: "button" %>
      </li>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/header" %>
    
    <div class="content">
      <%= render "layouts/flash" %>
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
    
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>
</section>